### ISSUE TITLE
Текущая версия содержит 2 ошибки

### ISSUE THREAD

**Issue by dukensk** [voskobovich/yii2-nested-sets-editor#1]
1. В NestableAsset неправильно указан $sourcePath. Должно быть:
   public $sourcePath = '@vendor/voskobovich/yii2-nested-sets-editor/src/widgets/nestable/assets';
2. В виджете Nestable игнорируется атрибут nameAttribute. 
   Необходимо заменить 127 строку с 
   echo $form->field($model, 'name');
   на 
   echo $form->field($model, $this->nameAttribute);

**Comment by voskobovich** [comment]
Спасибо!
Раз уж ты разобрался, отправь PR, чтобы я сразу выкатил фикс.

**Comment by voskobovich** [comment]
Так же, я рекомендую использовать https://github.com/voskobovich/yii2-tree-manager из-за интеграции с пачкой крутых поведений для работы с деревьями.
На странице поведения есть вся информация.
